---
version: 0.3

# Variables needed for this script are stored on Travis Settings
  # For all environments:
    # - DOCKER_CI_REPO_NAME
    # - DOCKER_USERNAME
    # - DOCKER_PASSWORD

env:
  variables:
    # n/a
  parameter-store:
    IMAGE_REPO_NAME: DOCKER_CI_REPO_NAME
    DOCKER_USERNAME: DOCKER_USERNAME
    DOCKER_PASSWORD: DOCKER_PASSWORD

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - echo Build starting on `date`
      - echo Build the Docker image...
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - test "$CODEBUILD_BUILD_SUCCEEDING" == "1" || exit 1
      - echo Pushing build to Docker Hub...
      - docker push $IMAGE_REPO_NAME:latest
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' bugzilla $IMAGE_REPO_NAME:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imagedefinitions.json

artifacts:
  files: imagedefinitions.json
