#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' # No Color

for stage in dev prod demo
do
	echo "--> $stage <--"
	aws --profile uneet-$stage ecs list-clusters | jq -r .clusterArns[] | while read cluster
	do
			echo cluster: $cluster
	aws --profile uneet-$stage ecs list-services --cluster $cluster | jq -r .serviceArns[] | while read service
	do
		echo aws --profile uneet-$stage ecs describe-services --cluster $cluster --services $service
		aws --profile uneet-$stage ecs describe-services --cluster $cluster --services $service | jq -r ".services[].loadBalancers[].targetGroupArn" | 
			while read target
			do
				echo target $target
				aws --profile uneet-$stage elbv2 describe-target-groups --target-group-arns $target
				aws --profile uneet-$stage elbv2 describe-target-group-attributes --target-group-arn $target
				if echo $target | grep bugzilla
				then
					stickiness=$(aws --profile uneet-$stage elbv2 describe-target-group-attributes --target-group-arn $target | 
						jq -r '.Attributes| from_entries."stickiness.enabled"')
					if test $stickiness != "true"
					then
						echo ""
						echo -e ${RED}ERROR${NC}: $target missing stickiness
						echo ""
						echo ""
					fi
				fi
			done
	done
	done
done
