#!/bin/bash

for stage in dev prod demo
do
	echo $stage
	source aws-env.$stage
	aws --profile $AWS_PROFILE ecs list-clusters | jq -r .clusterArns[] | while read cluster
	do
			echo cluster: $cluster
	aws --profile $AWS_PROFILE ecs list-services --cluster $cluster | jq -r .serviceArns[] | while read service
	do
		aws --profile $AWS_PROFILE ecs describe-services --cluster $cluster --services $service --query services[0].events[].message
	done
	done
done
