#!/bin/bash
for stage in dev prod demo
do
	echo $stage
	source aws-env.$stage
	aws --profile $AWS_PROFILE ecs list-clusters | jq -r .clusterArns[] | while read cluster
	do
	echo cluster: $cluster
	aws --profile $AWS_PROFILE ecs list-tasks --cluster $cluster | jq -r .taskArns[] | while read task
		do
		aws --profile $AWS_PROFILE ecs describe-tasks --cluster $cluster --tasks $task | jq -r .tasks[].taskDefinitionArn | while read taskdef
		do
		echo task definition: $taskdef
		aws --profile $AWS_PROFILE ecs describe-task-definition --task-definition $taskdef | jq '.taskDefinition.containerDefinitions[].environment[] | select(.name=="COMMIT").value'
		done
		done
	done
done
